-- Major Market Report — registry of tracked markets.
--
-- One row per market we want to scan. Drives the scheduler (which markets
-- fire monthly) and the report UI (the pill strip + per-market headers).
-- Kept fully independent of public.clients/locations so customer data
-- and market data never cross-pollinate.
--
-- Identity is the slug — operators reference markets by their URL form
-- ("manhattan-ny"), and code in lib/markets.ts has to stay in sync.

CREATE TABLE IF NOT EXISTS public.mmr_markets (
  market_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        text NOT NULL UNIQUE,
  label       text NOT NULL,
  town        text NOT NULL,
  state       text NOT NULL,
  -- Tier lets us bucket the report into "top 15" vs an opt-in luxury
  -- ring later without redesigning. 1 = always-on watchlist.
  tier        int  NOT NULL DEFAULT 1,
  active      boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mmr_markets_active_tier_idx
  ON public.mmr_markets (active, tier, slug);

-- Seed the 15 starter markets — same list as lib/markets.ts.
INSERT INTO public.mmr_markets (slug, label, town, state) VALUES
  ('manhattan-ny',     'Manhattan, NY',     'manhattan',     'NY'),
  ('los-angeles-ca',   'Los Angeles, CA',   'los angeles',   'CA'),
  ('chicago-il',       'Chicago, IL',       'chicago',       'IL'),
  ('houston-tx',       'Houston, TX',       'houston',       'TX'),
  ('dallas-tx',        'Dallas, TX',        'dallas',        'TX'),
  ('austin-tx',        'Austin, TX',        'austin',        'TX'),
  ('phoenix-az',       'Phoenix, AZ',       'phoenix',       'AZ'),
  ('miami-fl',         'Miami, FL',         'miami',         'FL'),
  ('atlanta-ga',       'Atlanta, GA',       'atlanta',       'GA'),
  ('seattle-wa',       'Seattle, WA',       'seattle',       'WA'),
  ('denver-co',        'Denver, CO',        'denver',        'CO'),
  ('boston-ma',        'Boston, MA',        'boston',        'MA'),
  ('washington-dc',    'Washington, DC',    'washington dc', 'DC'),
  ('san-francisco-ca', 'San Francisco, CA', 'san francisco', 'CA'),
  ('nashville-tn',     'Nashville, TN',     'nashville',     'TN')
ON CONFLICT (slug) DO NOTHING;

ALTER TABLE public.mmr_markets ENABLE ROW LEVEL SECURITY;

-- Anyone authenticated can read the registry — it's reference data, not
-- secret. Writes go through the scoring backend's service-role key,
-- which bypasses RLS automatically.
CREATE POLICY "authenticated_read_markets"
  ON public.mmr_markets
  FOR SELECT
  TO authenticated
  USING (true);
